# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: GitHub520

on:
  push:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest
    steps:    
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: actions/checkout@v3
      with:
          persist-credentials: false
          fetch-depth: 0
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then sudo pip install -r requirements.txt; fi
    - name: run script
      run: |
        # fetch new ip content and update readme file
        sudo python fetch_ips.py
    - name: commit
      id: commit
      run: |
        git config --global user.email sunxuebangong@gmail.com
        git config --global user.name action_bot
        git add .
        git commit -m "update readme content"
      continue-on-error: true
    - name: Check on failures
      if: steps.commit.outputs.status == 'failure'
      run: exit 1
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.GIT_TOKEN}}
        repository: tony252/GitHub520
        branch: ${{ github.ref }}
        directory: .

